
package org.example.proxy;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebService(name = "BanqueService", targetNamespace = "http://ws.example.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanqueService {


    /**
     * 
     * @param montant
     * @return
     *     returns double
     */
    @WebMethod(operationName = "ConversionEuroToDirham")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ConversionEuroToDirham", targetNamespace = "http://ws.example.org/", className = "org.example.proxy.ConversionEuroToDirham")
    @ResponseWrapper(localName = "ConversionEuroToDirhamResponse", targetNamespace = "http://ws.example.org/", className = "org.example.proxy.ConversionEuroToDirhamResponse")
    @Action(input = "http://ws.example.org/BanqueService/ConversionEuroToDirhamRequest", output = "http://ws.example.org/BanqueService/ConversionEuroToDirhamResponse")
    public double conversionEuroToDirham(
        @WebParam(name = "montant", targetNamespace = "")
        double montant);

    /**
     * 
     * @return
     *     returns java.util.List<org.example.proxy.Compte>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listeComptes", targetNamespace = "http://ws.example.org/", className = "org.example.proxy.ListeComptes")
    @ResponseWrapper(localName = "listeComptesResponse", targetNamespace = "http://ws.example.org/", className = "org.example.proxy.ListeComptesResponse")
    @Action(input = "http://ws.example.org/BanqueService/listeComptesRequest", output = "http://ws.example.org/BanqueService/listeComptesResponse")
    public List<Compte> listeComptes();

    /**
     * 
     * @param code
     * @return
     *     returns org.example.proxy.Compte
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCompte", targetNamespace = "http://ws.example.org/", className = "org.example.proxy.GetCompte")
    @ResponseWrapper(localName = "getCompteResponse", targetNamespace = "http://ws.example.org/", className = "org.example.proxy.GetCompteResponse")
    @Action(input = "http://ws.example.org/BanqueService/getCompteRequest", output = "http://ws.example.org/BanqueService/getCompteResponse")
    public Compte getCompte(
        @WebParam(name = "code", targetNamespace = "")
        int code);

}
